# This is name of workflow that will be dispalyed in the Action tba
name: CICD
#manual click (deliver workflow whenever user need

on:
  workflow_dispatch:
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        step: echo "code clone from github"
    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        step: echo "code clone from github"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        step: echo "testing the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        step: echo "Docker compose deployed the app"
