name: hello

on:
  push:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Hello to user
        run: echo "hello dostooo0000"

      - name: Say hello username
        run: echo "hello $USER"
