name: CI/CD pipeline
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
            - runs: git clone repository-url
            - name: install dependencies
            - run: npm install
            - name: run tests
            - run: npm test