name: DevOps Test Pipeline

on: 
 workflow_dispatch: 
   inputs:
      environment:
        description:  this  is the env value where the wokr flow  run
        default: 'dev'
        required: true
        type: choice
        - dev
        - prod
        - stage
      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Pipeline running successfully"
