name: DevOps Test Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Pipeline running successfully"
