# this is name of the workflow that will be displayed in the Actions Tab
name: cicd

# Manual trigger workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    needs: [code]
    runs-on: ubuntu-22.04
    steps:
      - name: Build docker container
        run: echo "Docker container1 build"

  test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    if: ${{ inputs.environment == 'dev' }}
    needs: [build, test]
    runs-on: ubuntu-22.04
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
