name: hello

on:
  push:
    branches: [ main ]
    paths: 
      - '**.html'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Hello to user
        run: echo "hello dostooo"

      - name: Say hello username
        run: echo "hello $USER"
